/**
 * Dynamic Core Functionality Extractor Routes
 * API endpoints for scanning test repositories (AMCC_NEWFRAME_CLONE1)
 * and retrieving the dynamic core functionality test suite at any coverage percentage.
 */

const express = require('express');
const router = express.Router();
const amccAnalyzer = require('../services/analyzer/amccAnalyzer');
const logger = require('../utils/logger');

/**
 * GET /api/core-suite/amcc
 * Retrieve the Dynamic Core Functionality Analysis for AMCC_NEWFRAME_CLONE1
 * Query params:
 * - coverage: number (1-100, default 30)
 * - refresh: boolean
 */
router.get('/amcc', async (req, res) => {
  try {
    const forceRefresh = req.query.refresh === 'true';
    const coverage = req.query.coverage ? parseFloat(req.query.coverage) : 30;
    const analysis = await amccAnalyzer.analyzeRepository(undefined, coverage, forceRefresh);
    
    res.json({
      success: true,
      data: analysis
    });
  } catch (error) {
    logger.error('AMCC Dynamic Core Analysis failed:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to analyze repository',
      message: error.message
    });
  }
});

/**
 * GET /api/core-suite/check-sync
 * Lightweight sync check to verify if AMCC files changed on disk
 */
router.get('/check-sync', (req, res) => {
  try {
    const targetPath = req.query.repoPath || undefined;
    const currentFingerprint = amccAnalyzer.computeRepositoryFingerprint(targetPath || 'c:\\Users\\Administrator\\Downloads\\AMCC_NEWFRAME_CLONE1');
    const isCached = !!amccAnalyzer.cachedPool;
    const isSynced = isCached && amccAnalyzer.cachedPool.fingerprint.hash === currentFingerprint.hash;

    res.json({
      success: true,
      data: {
        synced: isSynced,
        currentFingerprint,
        cachedFingerprint: isCached ? amccAnalyzer.cachedPool.fingerprint : null,
        lastAnalyzedAt: isCached ? amccAnalyzer.cachedPool.analyzedAt : null
      }
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      error: 'Failed to check sync status',
      message: error.message
    });
  }
});

/**
 * POST /api/core-suite/analyze-path
 * Run Dynamic Core Analysis on a custom repository path
 */
router.post('/analyze-path', async (req, res) => {
  try {
    const { repoPath, coverage = 30 } = req.body;
    if (!repoPath || typeof repoPath !== 'string') {
      return res.status(400).json({
        success: false,
        error: 'Repository path is required'
      });
    }

    const analysis = await amccAnalyzer.analyzeRepository(repoPath.trim(), parseFloat(coverage) || 30, true);
    res.json({
      success: true,
      data: analysis
    });
  } catch (error) {
    logger.error('Path Dynamic Core Analysis failed:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to analyze specified path',
      message: error.message
    });
  }
});

/**
 * GET /api/core-suite/export/:format
 * Export the Dynamic Core Functionality Test Suite at the chosen coverage percentage
 */
router.get('/export/:format', async (req, res) => {
  try {
    const format = (req.params.format || 'json').toLowerCase();
    const coverage = req.query.coverage ? parseFloat(req.query.coverage) : 30;
    const analysis = await amccAnalyzer.analyzeRepository(undefined, coverage, false);

    const covLabel = `${coverage}Percent`;

    if (format === 'json') {
      res.setHeader('Content-Type', 'application/json');
      res.setHeader('Content-Disposition', `attachment; filename="AMCC_${covLabel}_Core_Suite.json"`);
      return res.json(analysis);
    }

    if (format === 'csv') {
      let csv = `Issue Key,Module,Feature/File,Scenario Title,Priority Score,Coverage (${coverage}%),Rank,Steps\n`;
      analysis.modules.forEach(mod => {
        mod.coreTestCases.forEach(tc => {
          const stepsStr = (tc.steps || []).join('; ').replace(/"/g, '""');
          csv += `"${tc.issueKey}","${mod.moduleName}","${tc.fileName}","${(tc.title || '').replace(/"/g, '""')}",${tc.score},"Top ${coverage}%",#${tc.coreRank},"${stepsStr}"\n`;
        });
      });
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename="AMCC_${covLabel}_Core_Suite.csv"`);
      return res.send(csv);
    }

    if (format === 'markdown') {
      let md = `# AMCC ${coverage}% Dynamic Core Functionality Test Suite Export\n`;
      md += `*Generated by InsightQA AI on ${new Date().toLocaleString()}*\n\n`;
      md += `### 📊 Summary Metrics\n`;
      md += `- **Coverage Target**: Top ${coverage}% Core Functionality\n`;
      md += `- **Total Repository Test Scenarios**: ${analysis.summary.grandTotalScenarios}\n`;
      md += `- **Selected Core Test Cases**: ${analysis.summary.grandTotalCoreScenarios} Test Cases\n`;
      md += `- **Modules Covered**: ${analysis.summary.totalModules} Modules\n`;
      md += `- **Execution Overhead Reduction**: ${analysis.summary.overallCompression}%\n`;
      md += `- **Estimated Execution Time Saved**: ~${analysis.summary.estimatedHoursSaved || 0} hours\n`;
      md += `- **Repository Test Files Scanned**: ${analysis.summary.totalFilesScanned || 0} files\n\n`;

      analysis.modules.forEach(mod => {
        md += `## Module: ${mod.moduleName} (${mod.coreCount || mod.core30Count} Core Test Cases / ${mod.totalScenarios} Total)\n\n`;
        md += `| Rank | Key | Scenario Title | Priority Score | File Source |\n|---|---|---|---|---|\n`;
        mod.coreTestCases.forEach(tc => {
          md += `| #${tc.coreRank} | \`${tc.issueKey}\` | ${(tc.title || '').replace(/\|/g, '-')} | ${(tc.score || 0).toFixed(1)} | \`${tc.fileName}\` |\n`;
        });
        md += `\n---\n\n`;
      });

      res.setHeader('Content-Type', 'text/markdown');
      res.setHeader('Content-Disposition', `attachment; filename="AMCC_${covLabel}_Core_Suite.md"`);
      return res.send(md);
    }

    res.status(400).json({
      success: false,
      error: `Export format '${format}' is not supported. Use json, csv, or markdown.`
    });
  } catch (error) {
    logger.error('Export core suite failed:', error);
    res.status(500).json({
      success: false,
      error: 'Failed to export core suite'
    });
  }
});

module.exports = router;
